### ISSUE TITLE
soft

### ISSUE THREAD

**Issue by Sonya21** [brichard19/ecdl#3]
wait for the soft ,I think I get to take the prize on small degrees ,was laid out to test the capabilities of finding collisions. it will be ready reply to this message and write your bitcoin address I will give you a new video card with a money prize.

**Comment by brichard19** [comment]
Hi there,

I created a prototype tool. It is hosted at https://github.com/brichard19/BitCrack. Check it out and let me know what you think, and what features you think should be added.

Thanks.

**Comment by brichard19** [comment]
You can find a Windows binary here: https://github.com/brichard19/BitCrack/releases

**Comment by Sonya21** [comment]
Hi / how to use the -r, --range parameter ,show an example
